version = "v1.0.1b1"
currentFS: int = 0
image_option: int = 0
partition_scheme: int = 0
target_system: int = 0
cluster_size: int = 0
QF: int = 0
create_extended: int = 0
check_bad: int = 0
new_label: str = "USB_DRIVE"
iso_path: str = ""
DN: str = ""
currentflash: int = 0
language: str = "English"
verify_hash: bool = False
expected_hash: str = ""
winhardware = 0
winmicrosoftacc = 0
winlocalacc = 'default'
winprivacy = 0
