name: Build AppImage

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libfuse2 \
            libglib2.0-0 \
            libgl1 \
            libegl1 \
            libdbus-1-3 \
            libxcb-cursor0

      - name: Run build script
        run: bash appimage-setup-script.sh
        env:
          APPIMAGE_EXTRACT_AND_RUN: 1

      - name: Upload AppImage
        uses: actions/upload-artifact@v4
        with:
          name: Lufus-AppImage
          path: "*.AppImage"
          if-no-files-found: error
